const express = require('express');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const { exec, transaction } = require('../db');
const { requireAdmin, csrf, destroySession, setCookie, clearCookie, createSession } = require('../middleware/auth');
const { safeInt, safeMoney, slugify, bool, parseJson, cleanText, validHttpUrl, normalizePhone } = require('../lib/utils');

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 2 * 1024 * 1024, files: 1 }, fileFilter: (_req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype)) });
const loginHits = new Map();
function loginAllowed(ip){ const now=Date.now(); const v=loginHits.get(ip)||{count:0,start:now}; if(now-v.start>15*60_000){loginHits.set(ip,{count:1,start:now});return true;} v.count++; loginHits.set(ip,v); return v.count<=10; }
function sanitizeImage(v){ const s=String(v||'').trim(); return s.length<=1000?s:''; }
function sanitizeVariants(v){ if(Array.isArray(v)) return JSON.stringify(v.slice(0,30).map(x=>({name:cleanText(x.name,80),options:Array.isArray(x.options)?x.options.slice(0,30).map(o=>cleanText(o,80)).filter(Boolean):[]})).filter(x=>x.name)); return '[]'; }

router.post('/login', async (req,res,next)=>{
  try{
    if(!loginAllowed(req.ip)) return res.status(429).json({error:'Too many login attempts. Try again later.'});
    const email=cleanText(req.body?.email,160).toLowerCase(); const password=String(req.body?.password||'');
    const r=await exec('SELECT * FROM admins WHERE email=?',[email]);
    if(!r.rows[0] || !(await bcrypt.compare(password,r.rows[0].password_hash))) return res.status(401).json({error:'Invalid email or password.'});
    const s=await createSession(Number(r.rows[0].id)); setCookie(res,s.token); res.json({success:true});
  }catch(e){next(e);}
});
router.post('/logout', requireAdmin, csrf, async (req,res,next)=>{try{await destroySession(req);clearCookie(res);res.json({success:true});}catch(e){next(e);}});
router.get('/me', requireAdmin, (req,res)=>res.json({authenticated:true,email:req.admin.email,csrf:req.adminSession.csrf_token,expires_at:req.adminSession.expires_at}));

router.get('/dashboard',requireAdmin,async(_req,res,next)=>{try{
  const [orders,pending,confirmed,cancelled,revenue,products,services,reviews,leads,recent,low]=await Promise.all([
    exec('SELECT COUNT(*) c FROM orders'),exec("SELECT COUNT(*) c FROM orders WHERE order_status='pending'"),exec("SELECT COUNT(*) c FROM orders WHERE order_status='confirmed'"),exec("SELECT COUNT(*) c FROM orders WHERE order_status='cancelled'"),exec("SELECT COALESCE(SUM(total),0) revenue FROM orders WHERE payment_status='paid' OR payment_method='cod'"),exec('SELECT COUNT(*) c FROM products WHERE active=1'),exec('SELECT COUNT(*) c FROM services WHERE enabled=1'),exec('SELECT COUNT(*) c FROM reviews WHERE enabled=1'),exec("SELECT COUNT(*) c FROM leads WHERE status='new'"),exec(`SELECT o.order_code,o.total,o.order_status,o.payment_method,o.created_at,c.name customer_name FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT 8`),exec('SELECT id,name,stock,image_url FROM products WHERE active=1 AND stock<=5 ORDER BY stock ASC,name LIMIT 10')
  ]);
  res.json({stats:{orders:orders.rows[0].c,pending:pending.rows[0].c,confirmed:confirmed.rows[0].c,cancelled:cancelled.rows[0].c,revenue:Number(revenue.rows[0].revenue||0),products:products.rows[0].c,services:services.rows[0].c,reviews:reviews.rows[0].c,new_leads:leads.rows[0].c},recent_orders:recent.rows,low_stock:low.rows});
}catch(e){next(e);}});

router.get('/settings',requireAdmin,async(_req,res,next)=>{try{const r=await exec('SELECT key,value FROM settings ORDER BY key');res.json(Object.fromEntries(r.rows.map(x=>[x.key,x.value])));}catch(e){next(e);}});
router.put('/settings',requireAdmin,csrf,async(req,res,next)=>{try{for(const [k,v] of Object.entries(req.body||{})){if(!/^[a-z0-9_]{1,80}$/.test(k))continue; if(['whatsapp','phone'].includes(k)&&v&&!normalizePhone(v))continue; await exec('INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP',[k,cleanText(v,5000)]);}res.json({success:true});}catch(e){next(e);}});

router.get('/categories',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM categories ORDER BY sort_order,name')).rows);}catch(e){next(e);}});
router.post('/categories',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Category name is required.'});const slug=slugify(b.slug||b.name);const r=await exec('INSERT INTO categories(name,slug,description,image_url,active,sort_order) VALUES(?,?,?,?,?,?)',[cleanText(b.name,100),slug,cleanText(b.description,500),sanitizeImage(b.image_url),bool(b.active)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){res.status(400).json({error:'Category could not be saved. Slug may already exist.'});}});
router.put('/categories/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Category name is required.'});await exec('UPDATE categories SET name=?,description=?,image_url=?,active=?,sort_order=? WHERE id=?',[cleanText(b.name,100),cleanText(b.description,500),sanitizeImage(b.image_url),bool(b.active)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/categories/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM categories WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/products',requireAdmin,async(_req,res,next)=>{try{const r=await exec(`SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.sort_order,p.created_at DESC`);res.json(r.rows.map(p=>({...p,gallery:parseJson(p.gallery_json,[]),variants:parseJson(p.variants_json,[])})));}catch(e){next(e);}});
router.post('/products',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Product name is required.'});if(!b.image_url)return res.status(400).json({error:'Primary product image is required.'});const slug=slugify(b.slug||b.name);if(!validHttpUrl(b.image_url) && !String(b.image_url||'').startsWith('/api/media/'))return res.status(400).json({error:'Invalid image URL.'});const r=await exec(`INSERT INTO products(category_id,name,slug,description,price,sale_price,stock,sku,image_url,gallery_json,variants_json,featured,active,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[safeInt(b.category_id)||null,cleanText(b.name,150),slug,cleanText(b.description,5000),safeMoney(b.price),b.sale_price===''||b.sale_price==null?null:safeMoney(b.sale_price),Math.max(0,safeInt(b.stock)),cleanText(b.sku,80),sanitizeImage(b.image_url),JSON.stringify(Array.isArray(b.gallery)?b.gallery.slice(0,20):[]),sanitizeVariants(b.variants),bool(b.featured)?1:0,bool(b.active===undefined?true:b.active)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){res.status(400).json({error:'Product could not be saved. The slug may already exist.'});}});
router.put('/products/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Product name is required.'});await exec(`UPDATE products SET category_id=?,name=?,description=?,price=?,sale_price=?,stock=?,sku=?,image_url=?,gallery_json=?,variants_json=?,featured=?,active=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[safeInt(b.category_id)||null,cleanText(b.name,150),cleanText(b.description,5000),safeMoney(b.price),b.sale_price===''||b.sale_price==null?null:safeMoney(b.sale_price),Math.max(0,safeInt(b.stock)),cleanText(b.sku,80),sanitizeImage(b.image_url),JSON.stringify(Array.isArray(b.gallery)?b.gallery.slice(0,20):[]),sanitizeVariants(b.variants),bool(b.featured)?1:0,bool(b.active)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/products/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/products/:id/permanent',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM products WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/services',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM services ORDER BY sort_order,id')).rows);}catch(e){next(e);}});
router.post('/services',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.title)return res.status(400).json({error:'Service title is required.'});const r=await exec('INSERT INTO services(title,description,image_url,icon,price,button_text,button_action,enabled,sort_order) VALUES(?,?,?,?,?,?,?,?,?)',[cleanText(b.title,120),cleanText(b.description,700),sanitizeImage(b.image_url),cleanText(b.icon,30),b.price===''?null:safeMoney(b.price),cleanText(b.button_text,80),cleanText(b.button_action,300),bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){next(e);}});
router.put('/services/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};await exec('UPDATE services SET title=?,description=?,image_url=?,icon=?,price=?,button_text=?,button_action=?,enabled=?,sort_order=? WHERE id=?',[cleanText(b.title,120),cleanText(b.description,700),sanitizeImage(b.image_url),cleanText(b.icon,30),b.price===''?null:safeMoney(b.price),cleanText(b.button_text,80),cleanText(b.button_action,300),bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/services/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM services WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/landing',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM landing_sections ORDER BY sort_order,id')).rows.map(s=>({...s,content:parseJson(s.content_json,{})})));}catch(e){next(e);}});
router.post('/landing',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.section_key||!b.type)return res.status(400).json({error:'Section key and type are required.'});const r=await exec('INSERT INTO landing_sections(section_key,type,title,subtitle,body,image_url,button_text,button_url,content_json,enabled,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[slugify(b.section_key),cleanText(b.type,40),cleanText(b.title,200),cleanText(b.subtitle,200),cleanText(b.body,5000),sanitizeImage(b.image_url),cleanText(b.button_text,100),cleanText(b.button_url,300),JSON.stringify(b.content||{}),bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){res.status(400).json({error:'Section could not be added. Section key must be unique.'});}});
router.put('/landing/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};await exec('UPDATE landing_sections SET title=?,subtitle=?,body=?,image_url=?,button_text=?,button_url=?,content_json=?,enabled=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[cleanText(b.title,200),cleanText(b.subtitle,200),cleanText(b.body,5000),sanitizeImage(b.image_url),cleanText(b.button_text,100),cleanText(b.button_url,300),JSON.stringify(b.content||{}),bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/landing/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM landing_sections WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/faqs',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM faqs ORDER BY sort_order,id')).rows);}catch(e){next(e);}});
router.post('/faqs',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.question||!b.answer)return res.status(400).json({error:'Question and answer are required.'});const r=await exec('INSERT INTO faqs(question,answer,enabled,sort_order) VALUES(?,?,?,?)',[cleanText(b.question,500),cleanText(b.answer,3000),bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){next(e);}});
router.put('/faqs/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};await exec('UPDATE faqs SET question=?,answer=?,enabled=?,sort_order=? WHERE id=?',[cleanText(b.question,500),cleanText(b.answer,3000),bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/faqs/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM faqs WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/reviews',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM reviews ORDER BY sort_order,id')).rows);}catch(e){next(e);}});
router.post('/reviews',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};const rating=Math.max(1,Math.min(5,safeInt(b.rating,5)));if(!b.customer_name||!b.quote)return res.status(400).json({error:'Customer name and review text are required.'});const r=await exec('INSERT INTO reviews(customer_name,rating,quote,image_url,enabled,sort_order) VALUES(?,?,?,?,?,?)',[cleanText(b.customer_name,120),rating,cleanText(b.quote,1500),sanitizeImage(b.image_url),bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){next(e);}});
router.put('/reviews/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};const rating=Math.max(1,Math.min(5,safeInt(b.rating,5)));if(!b.customer_name||!b.quote)return res.status(400).json({error:'Customer name and review text are required.'});await exec('UPDATE reviews SET customer_name=?,rating=?,quote=?,image_url=?,enabled=?,sort_order=? WHERE id=?',[cleanText(b.customer_name,120),rating,cleanText(b.quote,1500),sanitizeImage(b.image_url),bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/reviews/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM reviews WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/testimonials',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM testimonials ORDER BY sort_order,id')).rows);}catch(e){next(e);}});
router.post('/testimonials',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.name||!b.quote)return res.status(400).json({error:'Name and quote are required.'});const r=await exec('INSERT INTO testimonials(name,role,quote,avatar_url,enabled,sort_order) VALUES(?,?,?,?,?,?)',[cleanText(b.name,120),cleanText(b.role,120),cleanText(b.quote,1000),sanitizeImage(b.avatar_url),bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){next(e);}});
router.put('/testimonials/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};await exec('UPDATE testimonials SET name=?,role=?,quote=?,avatar_url=?,enabled=?,sort_order=? WHERE id=?',[cleanText(b.name,120),cleanText(b.role,120),cleanText(b.quote,1000),sanitizeImage(b.avatar_url),bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/testimonials/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM testimonials WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/socials',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM social_links ORDER BY sort_order,id')).rows);}catch(e){next(e);}});
router.post('/socials',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!b.platform||!b.url||!validHttpUrl(b.url))return res.status(400).json({error:'Platform and valid URL are required.'});const r=await exec('INSERT INTO social_links(platform,label,url,enabled,sort_order) VALUES(?,?,?,?,?)',[cleanText(b.platform,50),cleanText(b.label||b.platform,80),b.url,bool(b.enabled)?1:0,safeInt(b.sort_order)]);res.status(201).json({id:Number(r.lastInsertRowid)});}catch(e){next(e);}});
router.put('/socials/:id',requireAdmin,csrf,async(req,res,next)=>{try{const b=req.body||{};if(!validHttpUrl(b.url))return res.status(400).json({error:'Valid URL required.'});await exec('UPDATE social_links SET platform=?,label=?,url=?,enabled=?,sort_order=? WHERE id=?',[cleanText(b.platform,50),cleanText(b.label,80),b.url,bool(b.enabled)?1:0,safeInt(b.sort_order),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/socials/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM social_links WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.post('/media',requireAdmin,csrf,upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'Please choose an image.'});const r=await exec('INSERT INTO media(filename,mime_type,data,size) VALUES(?,?,?,?)',[cleanText(req.file.originalname,200),req.file.mimetype,req.file.buffer,req.file.size]);res.status(201).json({id:Number(r.lastInsertRowid),url:`/api/media/${Number(r.lastInsertRowid)}`});}catch(e){next(e);}});
router.delete('/media/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM media WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/orders',requireAdmin,async(req,res,next)=>{try{const where=[];const args=[];if(req.query.status){where.push('o.order_status=?');args.push(req.query.status);}if(req.query.search){const q=`%${String(req.query.search).toLowerCase()}%`;where.push('(LOWER(o.order_code) LIKE ? OR LOWER(c.name) LIKE ? OR c.phone LIKE ?)');args.push(q,q,`%${String(req.query.search)}%`);}const r=await exec(`SELECT o.*,c.name customer_name,c.phone,c.email,c.address,c.city FROM orders o JOIN customers c ON c.id=o.customer_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY o.created_at DESC LIMIT 250`,args);res.json(r.rows);}catch(e){next(e);}});
router.get('/orders/:id',requireAdmin,async(req,res,next)=>{try{const r=await exec(`SELECT o.*,c.name customer_name,c.phone,c.email,c.address,c.city FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=?`,[safeInt(req.params.id)]);if(!r.rows[0])return res.status(404).json({error:'Order not found'});const items=await exec('SELECT * FROM order_items WHERE order_id=? ORDER BY id',[safeInt(req.params.id)]);res.json({...r.rows[0],items:items.rows});}catch(e){next(e);}});
router.put('/orders/:id',requireAdmin,csrf,async(req,res,next)=>{try{const allowedOrder=['pending','confirmed','processing','shipped','delivered','cancelled'];const allowedPay=['pending','paid','failed','refunded'];const status=String(req.body?.order_status||'pending');const pay=String(req.body?.payment_status||'pending');if(!allowedOrder.includes(status)||!allowedPay.includes(pay))return res.status(400).json({error:'Invalid status.'});await exec('UPDATE orders SET order_status=?,payment_status=?,internal_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[status,pay,cleanText(req.body?.internal_note,2000),safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.get('/leads',requireAdmin,async(_req,res,next)=>{try{res.json((await exec('SELECT * FROM leads ORDER BY created_at DESC LIMIT 300')).rows);}catch(e){next(e);}});
router.put('/leads/:id',requireAdmin,csrf,async(req,res,next)=>{try{const allowed=['new','contacted','resolved','archived'];const s=String(req.body?.status||'new');if(!allowed.includes(s))return res.status(400).json({error:'Invalid lead status.'});await exec('UPDATE leads SET status=? WHERE id=?',[s,safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});
router.delete('/leads/:id',requireAdmin,csrf,async(req,res,next)=>{try{await exec('DELETE FROM leads WHERE id=?',[safeInt(req.params.id)]);res.json({success:true});}catch(e){next(e);}});

router.post('/change-password',requireAdmin,csrf,async(req,res,next)=>{try{const current=String(req.body?.current_password||''),nextPw=String(req.body?.new_password||'');if(nextPw.length<12)return res.status(400).json({error:'New password must be at least 12 characters.'});const r=await exec('SELECT password_hash FROM admins WHERE id=?',[req.admin.id]);if(!r.rows[0]||!(await bcrypt.compare(current,r.rows[0].password_hash)))return res.status(401).json({error:'Current password is incorrect.'});const hash=await bcrypt.hash(nextPw,12);await transaction(async tx=>{await tx.execute('UPDATE admins SET password_hash=? WHERE id=?',[hash,req.admin.id]);await tx.execute('DELETE FROM admin_sessions WHERE admin_id=?',[req.admin.id]);});clearCookie(res);res.json({success:true});}catch(e){next(e);}});

module.exports=router;
